services:
  Backoffice.Courses.domain.CourseRepository:
    class: ../../../../../Contexts/Mooc/Courses/infrastructure/persistence/MongoCourseRepository
    arguments: ['@Backoffice.Shared.ConnectionManager']

  Backoffice.Courses.application.CourseCreator:
    class: ../../../../../Contexts/Mooc/Courses/application/CourseCreator
    arguments: ['@Backoffice.Courses.domain.CourseRepository', '@Backoffice.Shared.domain.EventBus']

  Backoffice.courses.CreateCourseCommandHandler:
    class: ../../../../../Contexts/Mooc/Courses/application/CreateCourseCommandHandler
    arguments: ['@Backoffice.Courses.application.CourseCreator']
    tags:
      - { name: 'commandHandler' }
