services:
  Apps.Backoffice.Backend.controllers.StatusGetController:
    class: ../../controllers/StatusGetController
    arguments: []

  Apps.Backoffice.Backend.controllers.CoursesPostController:
    class: ../../controllers/CoursesPostController
    arguments: ['@Backoffice.Shared.domain.CommandBus']