services:

  Mooc.Shared.MongoConfig:
    factory:
      class: ../../../../../Contexts/Mooc/Shared/infrastructure/persistence/mongo/MongoConfigFactory
      method: 'createConfig'

  Mooc.Shared.domain.EventBus:
    class: ../../../../../Contexts/Shared/infrastructure/EventBus/InMemory/InMemoryAsyncEventBus
    arguments: []

  Mooc.Shared.ConnectionManager:
    factory:
      class: ../../../../../Contexts/Shared/infrastructure/persistence/mongo/MongoClientFactory
      method: 'createClient'
    arguments: ['mooc', '@Mooc.Shared.MongoConfig']
