services:

  Apps.mooc.controllers.StatusGetController:
    class: ../../controllers/StatusGetController
    arguments: []

  Apps.mooc.controllers.CoursesPutController:
    class: ../../controllers/CoursesPutController
    arguments: []
